insert into investor_workspace.t_currency (cur_name) values ('Рубли');
insert into investor_workspace.t_indexes (indx_name) values ('IMOEX');

insert into investor_workspace.t_companies (cmpn_name) values ('Сбербанк');
insert into investor_workspace.t_companies (cmpn_name) values ('Газпром');
insert into investor_workspace.t_companies (cmpn_name) values ('Лукойл');
insert into investor_workspace.t_companies (cmpn_name) values ('Норникель');
insert into investor_workspace.t_companies (cmpn_name) values ('Яндекс');
insert into investor_workspace.t_companies (cmpn_name) values ('Новатэк');
insert into investor_workspace.t_companies (cmpn_name) values ('Роснефть');
insert into investor_workspace.t_companies (cmpn_name) values ('Полиметалл');
insert into investor_workspace.t_companies (cmpn_name) values ('Полюс');
insert into investor_workspace.t_companies (cmpn_name) values ('Магнит');
insert into investor_workspace.t_companies (cmpn_name) values ('Татнефть');
insert into investor_workspace.t_companies (cmpn_name) values ('Тинькофф');
insert into investor_workspace.t_companies (cmpn_name) values ('Сургутнефтегаз');
insert into investor_workspace.t_companies (cmpn_name) values ('X5 Retail Group');
insert into investor_workspace.t_companies (cmpn_name) values ('МТС');
insert into investor_workspace.t_companies (cmpn_name) values ('АЛРОСА');
insert into investor_workspace.t_companies (cmpn_name) values ('НЛМК');
insert into investor_workspace.t_companies (cmpn_name) values ('Московская Биржа');
insert into investor_workspace.t_companies (cmpn_name) values ('Северсталь');
insert into investor_workspace.t_companies (cmpn_name) values ('Mail.Ru Group');
insert into investor_workspace.t_companies (cmpn_name) values ('ИнтерРАО');
insert into investor_workspace.t_companies (cmpn_name) values ('ВТБ');
insert into investor_workspace.t_companies (cmpn_name) values ('Ozon.Ru');
insert into investor_workspace.t_companies (cmpn_name) values ('ФосАгро');
insert into investor_workspace.t_companies (cmpn_name) values ('ММК');
insert into investor_workspace.t_companies (cmpn_name) values ('Детский Мир');
insert into investor_workspace.t_companies (cmpn_name) values ('АФК Система');
insert into investor_workspace.t_companies (cmpn_name) values ('Ростелеком');
insert into investor_workspace.t_companies (cmpn_name) values ('Русал');
insert into investor_workspace.t_companies (cmpn_name) values ('Транснефть');
insert into investor_workspace.t_companies (cmpn_name) values ('PETROPAVLOVSK');
insert into investor_workspace.t_companies (cmpn_name) values ('Группа ПИК');
insert into investor_workspace.t_companies (cmpn_name) values ('Аэрофлот');
insert into investor_workspace.t_companies (cmpn_name) values ('Русгидро');
insert into investor_workspace.t_companies (cmpn_name) values ('Globaltrans');
insert into investor_workspace.t_companies (cmpn_name) values ('HeadHunter');
insert into investor_workspace.t_companies (cmpn_name) values ('ФСК ЕЭС');
insert into investor_workspace.t_companies (cmpn_name) values ('ЛСР Группа');
insert into investor_workspace.t_companies (cmpn_name) values ('МКБ');
insert into investor_workspace.t_companies (cmpn_name) values ('Россети');
insert into investor_workspace.t_companies (cmpn_name) values ('Юнипро');
insert into investor_workspace.t_companies (cmpn_name) values ('КИВИ (QIWI)');
